title: Adam Chen's Blog
email: progmdong@gmail.com

# Build setting
markdown: kramdown
theme: minima
description: >- # this means to ignore newlines until "baseurl:"â
    My Tech Blog to Record Computer Graphics Learning
baseurl: ""
